config/routes.rb
Rails.application.routes.draw do
  
  resources :bill_payments do
    member do
      get :send_to_leads_online
    end
  end
  
  resources :bills do
    collection do
      get :line_item_fields
    end
    member do
      post :update_qb
      get :send_to_leads_online
      get :send_to_bwi
    end
  end
  
  resources :items do
    member do
      get :update_qb
    end
    collection do
      get :items_by_category
    end
  end
  
  resources :purchase_orders do
    collection do
      get :line_item_fields
    end
    member do
      post :update_qb
      get :download
      get :send_to_leads_online
    end
  end
  
  resources :purchases
  
  resources :quickbooks do
    collection do
      get :authenticate
      get :oauth_callback
    end
  end
  
  resources :vendors do
    member do
      post :update_qb
    end
  end
  
  resources :lookup_defs
  
  resources :user_settings do
    collection do
      post :set_user_location
    end
  end
  
  resources :tud_devices do
    collection do
      get :drivers_license_scan
      get :scale_read
      get :show_scanned_jpeg_image
    end
  end
  
  resources :devices do
    member do
      get :drivers_license_scan
      get :scale_read
      get :scale_camera_trigger
      get :show_scanned_jpeg_image
      get :drivers_license_camera_trigger
      get :get_signature
      get :call_printer_for_purchase_order_pdf
      get :finger_print_trigger
      get :scanner_trigger
    end
    collection do
      get :customer_camera_trigger
      get :customer_scanner_trigger
      get :customer_scale_camera_trigger
      get :customer_camera_trigger_from_ticket
      get :drivers_license_camera_trigger_from_ticket
    end
  end
  
  
  resources :jpegger_contracts
  
  require 'sidekiq/web'
  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    username == ENV["SIDEKIQ_USERNAME"] && password == ENV["SIDEKIQ_PASSWORD"]
  end if Rails.env.production?
  mount Sidekiq::Web => '/sidekiq'
  
  resources :image_files
  
  resources :shipment_files
  
  resources :cust_pic_files

  
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  
  resources :images do
    member do
      get 'show_jpeg_image'
      get 'show_preview_image'
      get 'send_pdf_data'
    end
    collection do
      get 'advanced_search'
    end
  end
  
  resources :shipments do
    member do
      get 'show_jpeg_image'
      get 'show_preview_image'
    end
  end
  
  resources :cust_pics do
    member do
      get 'show_jpeg_image'
      get 'show_preview_image'
      get 'send_pdf_data'
    end
  end
  
  resources :companies

  root 'welcome#index'
  
  get 'welcome/privacy' => 'welcome#privacy'
  get 'welcome/tos' => 'welcome#tos'
  get 'welcome/about' => 'welcome#about'
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  

end

app/views/shared/_bill_footer_navbar.html.haml
.navbar.navbar-default.navbar-fixed-bottom{ role: 'navigation'}
  .container-fluid
    .navbar-header
      %div{class: 'navbar-brand navbar-center'}
        .col-xs-4.col-sm-4
          - current_user.finger_print_reader_devices.each do |finger_print_reader_device|
            %a{href: '#', class: 'finger_print_trigger', 'data-device-id' => finger_print_reader_device.id, 'data-ticket-number' => @doc_number, 'data-company-id' => current_company.id, 'data-customer-name' => @vendor.display_name, 'data-vendor-id' => @vendor.id }
              %i.fa.fa-hand-pointer-o.fa-lg
              = "Reader" unless mobile_device?
        .col-xs-4.col-sm-4
          -# 
            if params[:controller] == "images" or params[:controller] == "shipments"
          %a{href: "#upload_form", "data-toggle" => "modal", :alt => "new_image_file_form"}
            %i.fa.fa-camera.fa-lg
            = "Picture" unless mobile_device?
        .col-xs-4.col-sm-4
          - unless current_user.signature_pad_devices.blank?
            - current_user.signature_pad_devices.each do |signature_pad_device|
              %a{href: '#', class: 'tud_signature_pad', 'data-device-id' => signature_pad_device.id, 'data-ticket-number' => @doc_number, 'data-company-id' => current_company.id, 'data-customer-name' => @vendor.display_name, 'data-vendor-id' => @vendor.id}
                %i.fa.fa-pencil.fa-lg
                %i.fa.fa-spinner.fa-lg.fa-spin{style: 'display:none;'}
                = "Sign" unless mobile_device?
          - else
            %a{href: "#signature_form", "data-toggle" => "modal", :alt => "new_signature_form"}
              %i.fa.fa-pencil.fa-lg
              = "Sign" unless mobile_device?
          -#
            %a{href: "#{current_user.images_table? ? images_path(today: true) : shipments_path(today: true)}"}
              %i.fa.fa-calendar-o.fa-lg
              = "Today" unless mobile_device?

= render partial: "#{current_user.user_setting.table_name.singularize}_files/upload_modal"
= render partial: "#{current_user.user_setting.table_name.singularize}_files/signature_modal"

app/views/shared/_bill_payment_footer_navbar.html.haml
.navbar.navbar-default.navbar-fixed-bottom{ role: 'navigation'}
  .container-fluid
    .navbar-header
      %div{class: 'navbar-brand navbar-center'}
        .col-xs-3.col-sm-3
          %a{href: root_path}
            %i.fa.fa-home.fa-lg
            = "Home" unless mobile_device?
        .col-xs-3.col-sm-3
          - current_user.finger_print_reader_devices.each do |finger_print_reader_device|
            %a{href: '#', class: 'finger_print_trigger', 'data-device-id' => finger_print_reader_device.id, 'data-ticket-number' => @doc_number, 'data-company-id' => current_company.id, 'data-customer-name' => @vendor.display_name, 'data-vendor-id' => @vendor.id }
              %i.fa.fa-hand-pointer-o.fa-lg
              = "Reader" unless mobile_device?
        .col-xs-3.col-sm-3
          %a{href: "#upload_form", "data-toggle" => "modal", :alt => "new_image_file_form"}
            %i.fa.fa-camera.fa-lg
            = "Picture" unless mobile_device?
        .col-xs-3.col-sm-3
          - unless current_user.signature_pad_devices.blank?
            - current_user.signature_pad_devices.each do |signature_pad_device|
              %a{href: '#', class: 'tud_signature_pad', 'data-device-id' => signature_pad_device.id, 'data-ticket-number' => @doc_number, 'data-company-id' => current_company.id, 'data-customer-name' => @vendor.display_name, 'data-vendor-id' => @vendor.id }
                %i.fa.fa-pencil.fa-lg
                %i.fa.fa-spinner.fa-lg.fa-spin{style: 'display:none;'}
                = "Sign" unless mobile_device?
          - else
            %a{href: "#signature_form", "data-toggle" => "modal", :alt => "new_signature_form"}
              %i.fa.fa-pencil.fa-lg
              = "Sign" unless mobile_device?

= render partial: "#{current_user.user_setting.table_name.singularize}_files/upload_modal"

app/views/shared/_bill_payments_footer_navbar.html.haml
.navbar.navbar-default.navbar-fixed-bottom{ role: 'navigation'}
  .container-fluid
    .navbar-header
      %div{class: 'navbar-brand navbar-center'}
        .col-xs-4.col-sm-4
          %a{href: root_path}
            %i.fa.fa-home.fa-lg
            = "Home" unless mobile_device?
        .col-xs-4.col-sm-4
          -#
            - if params[:controller] == "images" or params[:controller] == "shipments"
              %a{href: "#upload_form", "data-toggle" => "modal", :alt => "new_image_file_form"}
                %i.fa.fa-camera.fa-lg
                = "Picture" unless mobile_device?
        .col-xs-4.col-sm-4
          %a{href: "#new_vendor_form", "data-toggle" => "modal", :alt => "new_vendor_form"}
            %i.fa.fa-user-plus.fa-lg
            = "Vendor" unless mobile_device?

= render partial: "vendors/new_modal"

app/views/shared/_bills_footer_navbar.html.haml
.navbar.navbar-default.navbar-fixed-bottom{ role: 'navigation'}
  .container-fluid
    .navbar-header
      %div{class: 'navbar-brand navbar-center'}
        .col-xs-4.col-sm-4
          %a{href: root_path}
            %i.fa.fa-home.fa-lg
            = "Home" unless mobile_device?
        .col-xs-4.col-sm-4
          -#
            - if params[:controller] == "images" or params[:controller] == "shipments"
              %a{href: "#upload_form", "data-toggle" => "modal", :alt => "new_image_file_form"}
                %i.fa.fa-camera.fa-lg
                = "Picture" unless mobile_device?
        .col-xs-4.col-sm-4
          -#
            %a{href: "#new_vendor_form", "data-toggle" => "modal", :alt => "new_vendor_form"}
              %i.fa.fa-user-plus.fa-lg
              = "Vendor" unless mobile_device?

= render partial: "vendors/new_modal"

app/views/shared/_contract_footer_navbar.html.haml
.navbar.navbar-default.navbar-fixed-bottom{ role: 'navigation'}
  .container-fluid
    .navbar-header
      %div{class: 'navbar-brand navbar-center'}
        .col-xs-4.col-sm-4
          %a{href: root_path}
            %i.fa.fa-home.fa-lg
            = "Home" unless mobile_device?
        .col-xs-4.col-sm-4
          -#
            %a{href: "#upload_form", "data-toggle" => "modal", :alt => "new_image_file_form"}
              %i.fa.fa-camera.fa-lg
              = "Pictures" unless mobile_device?
        .col-xs-4.col-sm-4
          

app/views/shared/_contracts_footer_navbar.html.haml
.navbar.navbar-default.navbar-fixed-bottom{ role: 'navigation'}
  .container-fluid
    .navbar-header
      %div{class: 'navbar-brand navbar-center'}
        .col-xs-4.col-sm-4
          %a{href: root_path}
            %i.fa.fa-home.fa-lg
            = "Home" unless mobile_device?
        .col-xs-4.col-sm-4
          
        .col-xs-4.col-sm-4
          

app/views/shared/_footer.html.haml
%footer
  .container
    %hr
    %p.text-center
      = link_to "http://www.tranact.com" do
        = "TranAct • Copyright #{Date.today.year} • All rights reserved"
      •
      = link_to "Privacy", welcome_privacy_path
      •
      = link_to "Terms", welcome_tos_path

app/views/shared/_footer_navbar.html.haml
.navbar.navbar-default.navbar-fixed-bottom{ role: 'navigation'}
  .container-fluid
    .navbar-header
      %div{class: 'navbar-brand navbar-center'}
        .col-xs-4.col-sm-4
          %a{href: root_path}
            %i.fa.fa-home.fa-lg
            = "Home" unless mobile_device?
        .col-xs-4.col-sm-4
          - if (params[:controller] == "images") and (params[:action]=='index')
            %a{href: advanced_search_images_path}
              Advanced Search
          -#
            - if params[:controller] == "images" or params[:controller] == "shipments"
              %a{href: "#upload_form", "data-toggle" => "modal", :alt => "new_image_file_form"}
                %i.fa.fa-camera.fa-lg
                = "Picture" unless mobile_device?
        .col-xs-4.col-sm-4
          -#
            %a{href: "#", "data-toggle" => "modal", :alt => "new_vendor_form"}
              %i.fa.fa-plus.fa-lg
              = "Vendor" unless mobile_device?

=# render partial: "#{current_user.user_setting.table_name.singularize}_files/upload_modal"

app/views/shared/_home_footer_navbar.html.haml
.navbar.navbar-default.navbar-fixed-bottom{ role: 'navigation'}
  .container-fluid
    .navbar-header
      %div{class: 'navbar-brand navbar-center'}
        .col-xs-4.col-sm-4
          -#
            %a{href: "#search_form", "data-toggle" => "modal", :alt => "search_form"}
              %i.fa.fa-search.fa-lg
              = "Search" unless mobile_device?
        .col-xs-4.col-sm-4
          -#
            %a{href: "#upload_form", "data-toggle" => "modal", :alt => "new_image_file_form"}
              %i.fa.fa-camera.fa-lg
              = "Picture" unless mobile_device?
        .col-xs-4.col-sm-4
          -#
            %a{href: user_setting_path(current_user.user_setting), "data-toggle" => "modal", :alt => "search_form"}
              %i.fa.fa-gear.fa-lg
              = "Settings" unless mobile_device?

- unless current_user.blank?
  = render partial: "#{current_user.user_setting.table_name}/search_modal"
  =# render partial: "#{current_user.user_setting.table_name.singularize}_files/upload_modal"

app/views/shared/_navbar.html.haml
.navbar.navbar-default{ role: 'navigation'}
  .container-fluid
    .navbar-header
      %div{class: 'navbar-brand navbar-center'}
        .col-xs-4.col-sm-4
          = link_to 'javascript:history.back()' do
            %i.fa.fa-arrow-left.fa-lg
        .col-xs-4.col-sm-4
          = title

app/views/shared/_new_item_footer_navbar.html.haml
.navbar.navbar-default.navbar-fixed-bottom{ role: 'navigation'}
  .container-fluid
    .navbar-header
      %div{class: 'navbar-brand navbar-center'}
        .col-xs-4.col-sm-4
          %a{href: root_path}
            %i.fa.fa-home.fa-lg
            = "Home" unless mobile_device?
        .col-xs-4.col-sm-4
          -#
            - if params[:controller] == "images" or params[:controller] == "shipments"
              %a{href: "#upload_form", "data-toggle" => "modal", :alt => "new_image_file_form"}
                %i.fa.fa-camera.fa-lg
                = "Picture" unless mobile_device?
        .col-xs-4.col-sm-4
          -#
            %a{href: "#new_vendor_from_ticket_form", "data-toggle" => "modal", :alt => "new_vendor_form"}
              %i.fa.fa-user-plus.fa-lg
              = "Vendor" unless mobile_device?

=# render partial: "vendors/new_from_ticket_modal"

app/views/shared/_new_purchase_order_footer_navbar.html.haml
.navbar.navbar-default.navbar-fixed-bottom{ role: 'navigation'}
  .container-fluid
    .navbar-header
      %div{class: 'navbar-brand navbar-center'}
        .col-xs-4.col-sm-4
          %a{href: root_path}
            %i.fa.fa-home.fa-lg
            = "Home" unless mobile_device?
        .col-xs-4.col-sm-4
          -#
            - if params[:controller] == "images" or params[:controller] == "shipments"
              %a{href: "#upload_form", "data-toggle" => "modal", :alt => "new_image_file_form"}
                %i.fa.fa-camera.fa-lg
                = "Picture" unless mobile_device?
        .col-xs-4.col-sm-4
          %a{href: "#new_vendor_from_ticket_form", "data-toggle" => "modal", :alt => "new_vendor_form"}
            %i.fa.fa-user-plus.fa-lg
            = "Vendor" unless mobile_device?

= render partial: "vendors/new_from_ticket_modal"

app/views/shared/_purchase_order_footer_navbar.html.haml
.navbar.navbar-default.navbar-fixed-bottom{ role: 'navigation'}
  .container-fluid
    .navbar-header
      %div{class: 'navbar-brand navbar-center'}
        .col-xs-4.col-sm-4
          - current_user.finger_print_reader_devices.each do |finger_print_reader_device|
            %a{href: '#', class: 'finger_print_trigger', 'data-device-id' => finger_print_reader_device.id, 'data-ticket-number' => @doc_number, 'data-company-id' => current_company.id, 'data-customer-name' => @vendor.display_name, 'data-vendor-id' => @vendor.id }
              %i.fa.fa-hand-pointer-o.fa-lg
              %i.fa.fa-spinner.fa-lg.fa-spin{style: 'display:none;'}
              = "Reader" unless mobile_device?
        .col-xs-4.col-sm-4
          -# if params[:controller] == "images" or params[:controller] == "shipments"
          %a{href: "#upload_form", id: 'picture_upload_modal_link', "data-toggle" => "modal", :alt => "new_image_file_form"}
            %i.fa.fa-camera.fa-lg
            = "Pictures" unless mobile_device?
        .col-xs-4.col-sm-4
          - unless current_user.signature_pad_devices.blank?
            - current_user.signature_pad_devices.each do |signature_pad_device|
              %a{href: '#', class: 'tud_signature_pad', 'data-device-id' => signature_pad_device.id, 'data-ticket-number' => @doc_number, 'data-company-id' => current_company.id, 'data-customer-name' => @vendor.display_name, 'data-vendor-id' => @vendor.id }
                %i.fa.fa-pencil.fa-lg
                %i.fa.fa-spinner.fa-lg.fa-spin{style: 'display:none;'}
                = "Sign" unless mobile_device?
          - else
            %a{href: "#signature_form", "data-toggle" => "modal", :alt => "new_signature_form"}
              %i.fa.fa-pencil.fa-lg
              = "Sign" unless mobile_device?
          -#
            %a{href: "#{current_user.images_table? ? images_path(today: true) : shipments_path(today: true)}"}
              %i.fa.fa-calendar-o.fa-lg
              = "Today" unless mobile_device?

= render partial: "#{current_user.user_setting.table_name.singularize}_files/upload_modal"
= render partial: "#{current_user.user_setting.table_name.singularize}_files/signature_modal"

app/views/shared/_purchase_orders_footer_navbar.html.haml
.navbar.navbar-default.navbar-fixed-bottom{ role: 'navigation'}
  .container-fluid
    .navbar-header
      %div{class: 'navbar-brand navbar-center'}
        .col-xs-4.col-sm-4
          %a{href: root_path}
            %i.fa.fa-home.fa-lg
            = "Home" unless mobile_device?
        .col-xs-4.col-sm-4
          -#
            - if params[:controller] == "images" or params[:controller] == "shipments"
              %a{href: "#upload_form", "data-toggle" => "modal", :alt => "new_image_file_form"}
                %i.fa.fa-camera.fa-lg
                = "Picture" unless mobile_device?
        .col-xs-4.col-sm-4
          -#
            %a{href: "#new_vendor_form", "data-toggle" => "modal", :alt => "new_vendor_form"}
              %i.fa.fa-user-plus.fa-lg
              = "Vendor" unless mobile_device?

= render partial: "vendors/new_modal"