config/routes.rb
Rails.application.routes.draw do
  
  resources :bill_payments do
    member do
      get :send_to_leads_online
    end
  end
  
  resources :bills do
    collection do
      get :line_item_fields
    end
    member do
      post :update_qb
      get :send_to_leads_online
      get :send_to_bwi
    end
  end
  
  resources :items do
    member do
      get :update_qb
    end
    collection do
      get :items_by_category
    end
  end
  
  resources :purchase_orders do
    collection do
      get :line_item_fields
    end
    member do
      post :update_qb
      get :download
      get :send_to_leads_online
    end
  end
  
  resources :purchases
  
  resources :quickbooks do
    collection do
      get :authenticate
      get :oauth_callback
    end
  end
  
  resources :vendors do
    member do
      post :update_qb
    end
  end
  
  resources :lookup_defs
  
  resources :user_settings do
    collection do
      post :set_user_location
    end
  end
  
  resources :tud_devices do
    collection do
      get :drivers_license_scan
      get :scale_read
      get :show_scanned_jpeg_image
    end
  end
  
  resources :devices do
    member do
      get :drivers_license_scan
      get :scale_read
      get :scale_camera_trigger
      get :show_scanned_jpeg_image
      get :drivers_license_camera_trigger
      get :get_signature
      get :call_printer_for_purchase_order_pdf
      get :finger_print_trigger
      get :scanner_trigger
    end
    collection do
      get :customer_camera_trigger
      get :customer_scanner_trigger
      get :customer_scale_camera_trigger
      get :customer_camera_trigger_from_ticket
      get :drivers_license_camera_trigger_from_ticket
    end
  end
  
  
  resources :jpegger_contracts
  
  require 'sidekiq/web'
  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    username == ENV["SIDEKIQ_USERNAME"] && password == ENV["SIDEKIQ_PASSWORD"]
  end if Rails.env.production?
  mount Sidekiq::Web => '/sidekiq'
  
  resources :image_files
  
  resources :shipment_files
  
  resources :cust_pic_files

  
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  
  resources :images do
    member do
      get 'show_jpeg_image'
      get 'show_preview_image'
      get 'send_pdf_data'
    end
    collection do
      get 'advanced_search'
    end
  end
  
  resources :shipments do
    member do
      get 'show_jpeg_image'
      get 'show_preview_image'
    end
  end
  
  resources :cust_pics do
    member do
      get 'show_jpeg_image'
      get 'show_preview_image'
      get 'send_pdf_data'
    end
  end
  
  resources :companies

  root 'welcome#index'
  
  get 'welcome/privacy' => 'welcome#privacy'
  get 'welcome/tos' => 'welcome#tos'
  get 'welcome/about' => 'welcome#about'
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  

end

app/controllers/bills_controller.rb
class BillsController < ApplicationController
  before_filter :authenticate_user!
#  load_and_authorize_resource

  before_action :set_oauth_client
  before_action :set_bill_service, only: [:index, :show, :create, :edit, :update, :update_qb, :destroy, :send_to_leads_online, :send_to_bwi]
  before_action :set_vendor_service, only: [:index, :show, :new, :create, :edit, :update]
  before_action :set_item_service, only: [:index, :show, :new, :create, :edit, :line_item_fields]
  before_action :set_purchase_order_service, only: [:new, :create, :edit, :update, :update_qb, :destroy]
  before_action :set_bill_payment_service, only: [:show]
  before_action :set_account_service, only: [:index]
  before_action :set_company_service, only: [:show]
  
  before_action :set_bill, only: [:show, :edit, :update, :update_qb, :destroy, :send_to_leads_online, :send_to_bwi]

  # GET /bills
  # GET /bills.json
  def index
#    @vendors = @vendor_service.query(nil, :per_page => 1000)
#    @items = @item_service.query(nil, :per_page => 1000)
#    query = "Select * From Bill Where TxnDate>'#{1.month.ago.strftime("%Y-%m-%d")}'"
    query = "Select * From Bill Where TxnDate>'#{1.week.ago.strftime("%Y-%m-%d")}'"
    @open_bills = @bill_service.query(query, :per_page => 30).entries.find_all{ |e| e.balance > 0 }
    @open_bills = Kaminari.paginate_array(@open_bills).page(params[:page]).per(3)
#    @paid_bills = @bill_service.query(nil, :per_page => 20).entries.find_all{ |e| e.balance == 0 }

    ### Get bank information for quick pay option
    query_banks = "Select * from Account Where AccountType = 'Bank'"
    @bank_accounts = @account_service.query(query_banks, :per_page => 1000)
    @accounts = []
    @bank_accounts.each do |bank_account|
      @accounts.push(bank_account)
    end
    
  end

  # GET /bills/1
  # GET /bills/1.json
  def show
    @vendor = @vendor_service.fetch_by_id(@bill.vendor_ref)
    @doc_number = @bill.doc_number
#    @purchase_order = @purchase_order_service.query.entries.find{ |p| p.doc_number == @doc_number }
    
    respond_to do |format|
      format.html do
        @images = Image.where(ticket_nbr: @doc_number)
        @bill_payment = @bill_payment_service.query.entries.find{ |b| b.doc_number == @doc_number } if @bill.balance == 0
      end
      format.pdf do
        @signature_image = Image.where(ticket_nbr: @doc_number, location: current_company_id, event_code: "SIGNATURE CAPTURE").last
        @finger_print_image = Image.where(ticket_nbr: @doc_number, location: current_company_id, event_code: "Finger Print").last
        unless current_user.printer_devices.blank?
          printer = current_user.printer_devices.last
          render pdf: "Bill#{@doc_number}",
    #        :page_width => 4,
            :layout => 'pdf.html.haml',
  #          :zoom => 1.25,
            :zoom => "#{printer.PrinterWidth < 10 ? 2 : 1.25}",
            :save_to_file => Rails.root.join('pdfs', "#{current_company_id}Bill#{@doc_number}.pdf")
          printer.call_printer_for_bill_pdf(Base64.encode64(File.binread(Rails.root.join('pdfs', "#{current_company_id}Bill#{@doc_number}.pdf"))))
          # Remove the temporary pdf file that was created above
          FileUtils.remove(Rails.root.join('pdfs', "#{current_company_id}Bill#{@doc_number}.pdf"))
        else
          render pdf: "Bill#{@doc_number}",
          :layout => 'pdf.html.haml',
          :zoom => 1.25
        end
      end
    end
  end

  # GET /bills/new
  def new
    @vendors = @vendor_service.query(nil, :per_page => 1000)
#    query = "Select * From Item Where Type = 'Inventory'"
#    @items = @item_service.query(query, :per_page => 1000)
    @items = @item_service.query(nil, :per_page => 1000)
    @purchase_order = @purchase_order_service.fetch_by_id(params[:purchase_order_id])
  end

  # GET /bills/1/edit
  def edit
#    @vendors = @vendor_service.query(nil, :per_page => 1000)
    @vendor = @vendor_service.fetch_by_id(@bill.vendor_ref)
#    @customer = Customer.where(vendorid: @bill.vendor_ref.value, qb_company_id: current_company.CompanyID).last
    @doc_number = @bill.doc_number
#    @contract = Contract.find(current_company_id) # Find contract for this company
    
    query_string = "Select * From Item Where Type = 'NonInventory'"
    @items = @item_service.query(query_string, :per_page => 1000)
    
    category_query_string = "Select * From Item Where Type = 'Category'"
    @categories = @item_service.query(category_query_string, :per_page => 1000)
    
    @scale_devices = current_user.scale_devices
#    @images = Image.where(ticket_nbr: @doc_number, location: current_user.location)
  end
  
  # POST /bills
  # POST /bills.json
  def create
    @purchase_order = @purchase_order_service.fetch_by_id(params[:purchase_order_id])
    @bill = Quickbooks::Model::Bill.new
    @bill.vendor_id = @purchase_order.vendor_ref
    @bill.doc_number = bill_params[:doc_number]
    
    bill_params[:line_items].each do |line_item|
      item_based_expense_line_detail = Quickbooks::Model::ItemBasedExpenseLineDetail.new
      item_based_expense_line_detail.unit_price = line_item[:rate]
      item_based_expense_line_detail.quantity = line_item[:quantity]
      item_based_expense_line_detail.item_id= line_item[:item]

      bill_line_item = Quickbooks::Model::BillLineItem.new
      bill_line_item.detail_type = "ItemBasedExpenseLineDetail"
      bill_line_item.item_based_expense_line_detail = item_based_expense_line_detail
      bill_line_item.amount = line_item[:amount]
      bill_line_item.description = "#{line_item[:gross]} - #{line_item[:tare]}" unless (line_item[:gross].blank? or line_item[:tare].blank?)
      @bill.line_items.push(bill_line_item)
    end
    
    @bill = @bill_service.create(@bill)

    respond_to do |format|
      if @bill.present?
        @purchase_order.po_status = "Closed"
        @purchase_order_service.update(@purchase_order)
#        format.html { redirect_to bill_path(@bill.id), notice: 'Bill was successfully created.' }
        format.html { 
          if params[:pay_ticket]
            redirect_to new_bill_payment_path(bill_id: @bill.id)
          else
#            redirect_to purchase_orders_path 
            redirect_to root_path
          end
          }
        format.json { render :show, status: :created, location: bill_path(@bill.id) }
      else
        format.html { render :new }
        format.json { render json: @bill.errors, status: :unprocessable_entity }
      end
    end
  end

  def update_qb
    @bill.vendor_id = bill_params[:vendor]
    @bill.doc_number = bill_params[:doc_number]
    @bill.line_items.clear
    
    bill_params[:line_items].each do |line_item|
      item_based_expense_line_detail = Quickbooks::Model::ItemBasedExpenseLineDetail.new
      item_based_expense_line_detail.unit_price = line_item[:rate]
      item_based_expense_line_detail.quantity = line_item[:quantity]
      item_based_expense_line_detail.item_id= line_item[:item]

      bill_line_item = Quickbooks::Model::BillLineItem.new
      bill_line_item.detail_type = "ItemBasedExpenseLineDetail"
      bill_line_item.item_based_expense_line_detail = item_based_expense_line_detail
      bill_line_item.amount = line_item[:amount]
      unless (line_item[:gross].blank? and line_item[:tare].blank?)
        bill_line_item.description = "#{line_item[:gross]} - #{line_item[:tare]}"
      else
        bill_line_item.description = line_item[:description]
      end
      @bill.line_items.push(bill_line_item)
    end
    
    @bill = @bill_service.update(@bill)
    
    respond_to do |format|
      if @bill.present?
        format.html { 
          if params[:pay_ticket]
            redirect_to new_bill_payment_path(bill_id: @bill.id)
          else
#            redirect_to bill_path(@bill.id), notice: 'Bill was successfully updated.' 
#            redirect_to purchase_orders_path
#            redirect_to bills_path
            redirect_to root_path
          end
          }
        format.json { render :show, status: :ok, location: bill_path(@bill.id) }
      else
        format.html { render :edit }
        format.json { render json: @bill.errors, status: :unprocessable_entity }
      end
    end
  end
  
  # PATCH/PUT /bills/1
  # PATCH/PUT /bills/1.json
  def update
    respond_to do |format|
      if @bill.update(bill_params)
        format.html { redirect_to @bill, notice: 'Bill was successfully updated.' }
        format.json { render :show, status: :ok, location: @bill }
      else
        format.html { render :edit }
        format.json { render json: @bill.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def line_item_fields
#    @items = @item_service.query(nil, :per_page => 1000)
    respond_to do |format|
      format.js
    end
  end

  # DELETE /bills/1
  # DELETE /bills/1.json
  def destroy
    @bill.destroy
    respond_to do |format|
      format.html { redirect_to bills_url, notice: 'Bill was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def send_to_leads_online
    @customer = Customer.where(vendorid: @bill.vendor_ref.value, qb_company_id: current_company.CompanyID).last
    
    path_to_file = "public/leads_online/f_0_#{current_company.leads_online_store_id}_#{Date.today.strftime("%m")}_#{Date.today.strftime("%d")}_#{Date.today.strftime("%Y")}_#{Time.now.strftime("%H%M%S")}.xml"
    SendBillToLeadsWorker.perform_async(current_user.qbo_access_credential.access_token, current_user.qbo_access_credential.access_secret, path_to_file, @bill.id, current_company_id, current_user.id, @customer.id)

    respond_to do |format|
      format.html { redirect_to bills_path, notice: 'Bill details sent to Leads Online.' }
    end
  end
  
  def send_to_bwi
    @customer = Customer.where(vendorid: @bill.vendor_ref.value, qb_company_id: current_company.CompanyID).last
    

app/views/bills/_quick_pay.html.haml
= form_tag bill_payments_path, id: 'bill_payment_form', :class => "form-inline" do |f|
  .form-group
    = hidden_field "bill_payment[vendor]", bill.vendor_ref
    = select_tag "bill_payment[pay_account]", options_from_collection_for_select(@accounts, "id", "name"), class: "form-control input-lg", required: true
    = hidden_field_tag "bill_payment[total]", bill.balance
    = hidden_field_tag "bill_payment[doc_number]", bill.doc_number
    = hidden_field_tag :bill_id, bill.id
  = button_tag(:type => 'submit', :class => 'btn btn-success btn-lg', data: {disable_with: "<i class='fa fa-spinner fa-spin'></i> Pay..."}, autocomplete: "off") do
    Pay

app/views/bills/edit.html.haml
= render partial: "shared/navbars/new_and_edit_bill_navbar", locals: {title: "#{@bill.doc_number}", total: number_to_currency(@bill.total)}
- @title="Closed #{@bill.doc_number}" 

.container
  = form_tag update_qb_bill_path, method: 'post', id: 'bill_form', :class => "form-horizontal" do
    #vendor_accordion.panel-group{"aria-multiselectable" => "true", :role => "tablist"}
      .panel.panel-default
        %div.panel-heading{:role => "tab", id: "vendor_heading"}
          %h4.panel-title
            %a.text-success{"aria-controls" => "collapseVendor", "aria-expanded" => "true", "data-parent" => "#vendor_accordion", "data-toggle" => "collapse", :href => "#collapseVendor", :role => "button"}
              #vendor_name.text-success= @bill.vendor_ref.name
        #collapseVendor.panel-collapse.collapse{"aria-labelledby" => "headingOne", :role => "tabpanel"}
          .panel-body
            %div.input-group
              - unless current_user.customer_camera.blank? or @vendor.blank?
                -# %span.input-group-addon
                %a{href: '#', style: "color: hotpink;", class: "customer_camera_trigger_from_ticket btn btn-default btn-lg", 'data-location' => current_user.location, 'data-given-name' => @vendor.given_name, 'data-family-name' => @vendor.family_name, 'data-vendor-id' => @vendor.id, 'data-camera-name' => current_user.customer_camera, title: current_user.customer_camera}
                  %i.fa.fa-camera.fa-lg
                  %i.fa.fa-spinner.fa-lg.fa-spin{style: 'display:none;'}
              =# select_tag "bill[vendor]", options_for_select(Rails.cache.fetch("all_vendors"), @vendor.id), prompt: "Choose a vendor", class: "form-control input-lg", required: true
              =# select_tag "bill[vendor]", options_from_collection_for_select(@vendors, "id", "display_name", @bill.vendor_ref), prompt: "Choose a vendor", class: "form-control input-lg", required: true
              = hidden_field_tag "bill[vendor]", @bill.vendor_ref
              = hidden_field_tag "bill[doc_number]", @bill.doc_number
        -#
          %div.panel-footer
            %ul{class: 'list-inline'}
              %li
                #vendor_name= @bill.vendor_ref.name
              %li.pull-right
                %a.text-success{"aria-controls" => "collapseVendor", "aria-expanded" => "true", "data-parent" => "#vendor_accordion", "data-toggle" => "collapse", :href => "#collapseVendor", :role => "button", class: "collapsed", onclick: "$(this).find('i').toggleClass('fa-check-square fa-chevron-down');" }
                  %i.fa.fa-chevron-down.fa-lg
    %div.bill_input_fields_wrap
      #items_accordion.panel-group{"aria-multiselectable" => "true", :role => "tablist"}
        - @bill.line_items.each do |line_item|
          .panel.panel-default.line-item
            %div.panel-heading{:role => "tab", id: "heading#{line_item.id}"}
              %h4.panel-title
                %ul{class: 'list-inline'}
                  %li
                    %a.line_item_name.text-success{"aria-controls" => "collapse#{line_item.id}", "aria-expanded" => false, "data-toggle" => "collapse", :href => "#collapse_#{line_item.id}", :role => "button", class: "collapsed bill_item_collapse_link"}
                      = line_item.item_based_expense_line_detail.item_ref.name
                  %li.pull-right
                    %a{href: '#', class: 'remove_field'}
                      %i.fa.fa-trash.fa-lg.text-danger
                = hidden_field_tag :item_description, @item_service.fetch_by_id(line_item.item_based_expense_line_detail.item_ref).purchase_desc
            %div{id: "collapse_#{line_item.id}", "aria-labelledby" => "heading#{line_item.id}", :role => "tabpanel", class: "panel-collapse collapse ", "aria-expanded" => false}
              .panel-body
                - unless @categories.count < 1
                  = select_tag "purchase_order[line_items][][category]", options_from_collection_for_select(@categories, "id", "name", @item_service.fetch_by_id(line_item.item_based_expense_line_detail.item_ref).parent_ref), prompt: 'All categories' , class: "form-control input-lg category_select"
                  %br
                =# select_tag "bill[line_items][][item]", options_from_collection_for_select(@items, "id", "name", line_item.item_based_expense_line_detail.item_ref), prompt: 'Choose an item' , class: "form-control input-lg item_select", required: true
                = select_tag "bill[line_items][][item]", options_for_select(@items.map{ |item| [item.name, item.id, { 'data-parent-ref' => item.parent_ref }] }, line_item.item_based_expense_line_detail.item_ref), prompt: 'Choose an item', class: "form-control input-lg item_select", required: true
                = hidden_field_tag "bill[line_items][][description]", line_item.description
                %br
                %div.input-group
                  %span.input-group-addon
                    %i.fa.fa-plus{style: "font-size:0.7em;"}
                  - unless line_item.description.blank?
                    = phone_field_tag "bill[line_items][][gross]", line_item.description.split(' - ').first, :placeholder => "Gross", class: "form-control input-lg amount-calculation-field"
                  - else
                    = phone_field_tag "bill[line_items][][gross]", 0, :placeholder => "Gross", class: "form-control input-lg amount-calculation-field"
                %br
                %div.input-group
                  %span.input-group-addon
                    %i.fa.fa-minus{style: "font-size:0.7em;"}
                  - unless line_item.description.blank?
                    = phone_field_tag "bill[line_items][][tare]", line_item.description.split(' - ').second, :placeholder => "Subtract", class: "form-control input-lg amount-calculation-field"
                  - else
                    = phone_field_tag "bill[line_items][][tare]", 0, :placeholder => "Subtract", class: "form-control input-lg amount-calculation-field"
                %br
                =# label_tag "Net", nil, :class => 'control-label'
                = hidden_field_tag "bill[line_items][][quantity]", line_item.item_based_expense_line_detail.quantity, :placeholder => "Net", class: "form-control input-lg amount-calculation-field", required: true, readonly: true
                %div.input-group
                  %span.input-group-addon
                    %i.fa.fa-dollar.fa-lg
                  = text_field_tag "bill[line_items][][rate]", number_with_precision(line_item.item_based_expense_line_detail.unit_price, :precision => 3), :placeholder => "Rate", class: "form-control input-lg amount-calculation-field", required: true
                = hidden_field_tag "bill[line_items][][amount]", number_with_precision(line_item.amount, :precision => 2), :placeholder => "Amount", class: "form-control input-lg amount", required: true, readonly: true
            %div.panel-footer
              %ul{class: 'list-inline'}
                %li.calculation_details
                  =# "(#{line_item.description}) ="
                  = "(#{line_item.description.split(' - ').first} - #{line_item.description.split(' - ').second}) ="
                  = "#{number_with_precision(line_item.item_based_expense_line_detail.quantity, :precision => 2)}#{@item_service.fetch_by_id(line_item.item_based_expense_line_detail.item_ref).purchase_desc}"
                  = " x $#{number_with_precision(line_item.item_based_expense_line_detail.unit_price, :precision => 3)}"
                  = "= #{number_to_currency(line_item.amount)}"
                %li.pull-right
                  %a.text-success{"aria-controls" => "collapse#{line_item.id}", "data-toggle" => "collapse", :href => "#collapse_#{line_item.id}", class: "pull-right bill_item_collapse_link" }
                    %i.fa.fa-3x.collapse_icon
    .row.form-group
      %div.col-xs-4.col-sm-4
        = image_tag("ajax-loader.gif", :id => "spinner", :alt => "Loading ...", style: "display:none;")
        %a{ href: line_item_fields_bills_path, 'data-remote' => true, id: "add_item_button", class: "btn btn-warning btn-lg btn-block", onclick: "$(this).hide(); $('#spinner').show();" }
          %i.fa.fa-plus
          Item
      %div.col-xs-4.col-sm-4
        = button_tag(:type => 'submit', :class => 'btn btn-primary btn-lg btn-block', id: 'save_button', name: 'save', data: {disable_with: "<i class='fa fa-spinner fa-spin'></i> Save"}, autocomplete: "off", onclick: "$(this).closest('.form-group').find('#pay_button').removeAttr('data-disable-with');") do
          %i.fa.fa-check.fa-lg
          Save
      %div.col-xs-4.col-sm-4
        = button_tag(pay_ticket: true, :type => 'submit', :class => 'btn btn-primary btn-lg btn-block', id: 'pay_button', name: 'pay_ticket', data: {disable_with: "<i class='fa fa-spinner fa-spin'></i> Pay"}, autocomplete: "off", onclick: "$(this).closest('.form-group').find('#save_button').removeAttr('data-disable-with');") do
          %i.fa.fa-dollar.fa-lg
          Pay
    %hr
    %div#images

    %div{id: 'endless_page'}
      %p= image_tag("ajax-loader.gif", :id => "more_images_spinner", :alt => "Loading ...", style: "display:none;")
      %p= link_to 'More pictures ...', images_path(:page => nil, :q => {ticket_nbr_eq: @bill.doc_number, location_eq: current_user.location}, :one_image_per_ticket => '0'), :class => 'load-more-images btn btn-default', :remote => true, :onclick => "$(this).hide(); $('#more_images_spinner').show();" #if @images.next_page
      %p= link_to 'Re-load pictures ...', images_path(:page => nil, :q => {ticket_nbr_eq: @bill.doc_number, location_eq: current_user.location}, :one_image_per_ticket => '0'), :class => 'reload-images btn btn-default', :remote => true, :onclick => "$(this).hide(); $('#more_images_spinner').show(); $('#images').empty(); $('a.load-more-images').attr('href', '<%= images_path page: @images.next_page, q: params[:q], one_image_per_ticket: params[:one_image_per_ticket] %>');", style: "display:none;" #if @images.next_page

= render partial: "shared/bill_footer_navbar", locals: {title: "Bill"}

app/views/bills/index.html.haml
= render partial: "shared/navbars/bills_navbar", locals: {title: "Closed"}
- @title="Closed" 

.container
  %p
    .btn-group
      = link_to "<i class='fa fa-users fa-lg'></i> Vendors".html_safe, vendors_path, :class => "btn btn-default btn-lg bill_button", id: 'bills_to_vendors', data: {disable_with: "<i class='fa fa-spinner fa-spin'></i> Vendors"}
      = link_to "<i class='fa fa-folder-open-o fa-lg'></i> Open".html_safe, purchase_orders_path, :class => "btn btn-default btn-lg bill_button", id: 'bills_to_open', data: {disable_with: "<i class='fa fa-spinner fa-spin'></i> Open"}
      %button{class: 'btn btn-default btn-lg active'}
        %i.fa.fa-folder.fa-lg
        Closed
  -#
    %p
      .btn-group
        = link_to "Paid", bill_payments_path, :class => "btn btn-default btn-lg bill_button", id: 'bills_to_bill_payments', data: {disable_with: "<i class='fa fa-spinner fa-spin'></i> Paid"}
        = link_to "Items", items_path, :class => "btn btn-default btn-lg bill_button", id: 'bills_to_items', data: {disable_with: "<i class='fa fa-spinner fa-spin'></i> Items"}
  
  - if @open_bills.blank?
    .jumbotron
      %p.text-center No closed tickets found
  - else
    -#
      %div.row
        .col-xs-12.col-sm-12.col-md-12
          %div.panel{style: 'border: 0;'}
            %div.panel-body
              %div.col-xs-4.col-sm-4.col-md-4.col-lg-4
                %strong Ticket
              %div.col-xs-4.col-sm-4.col-md-4.col-lg-4
                %strong Vendor
              %div.col-xs-4.col-sm-4.col-md-4.col-lg-4
                %strong Balance
    %div{id: 'open_bills'}
      - @open_bills.sort_by(&:txn_date).reverse.each do |bill|
        %div.row
          .col-xs-12.col-sm-12.col-md-12
            %div.panel.panel-primary
              %div.list_group
                %a{href: edit_bill_path(bill.id), class: "list-group-item bill_button", data: {disable_with: "<i class='fa fa-spinner fa-spin fa-lg'></i> #{bill.doc_number} #{bill.vendor_ref.name}"}}
                  .pull-right
                    &nbsp;
                    %i.fa.fa-chevron-right.fa-lg
                  - if current_user.user_setting.show_bill_thumbnails? and Image.where(ticket_nbr: bill.doc_number, location: current_company_id, event_code: "Gross").count > 0
                    =# image_tag(show_preview_image_image_path(Image.where(ticket_nbr: bill.doc_number, location: current_company_id, event_code: "Gross").last.id), class: 'thumbnail img-responsive')
                    = image_tag(Image.where(ticket_nbr: bill.doc_number, location: current_company_id, event_code: "Gross").last.preview_data_uri, class: 'thumbnail img-responsive')
                  = bill.doc_number
                  = bill.vendor_ref.name unless bill.vendor_ref.blank?
                  .pull-right
                    = number_to_currency(bill.balance)
                    
                %div.list-group-item
                  = bill.txn_date.strftime("%m/%d/%y")
                  .pull-right
                    - unless bill.private_note.blank?
                      %i= bill.private_note
                    %a.btn.btn-primary{class: "", "data-content" => "#{render partial: 'more_bill_options', locals: {bill: bill}}", "data-placement" => 'left', "data-html" => "true", "data-toggle" => "popover", :role => "button", :tabindex => "0", title: "Print, Pay, or Leads"}
                      More
                  %br
                  %br

  %div.row
    .text-center
      %div{id: 'endless_page'}
        %p= image_tag("ajax-loader.gif", :id => "spinner", :alt => "Loading ...", style: "display:none;")
        %p= link_to 'Load more ...', bills_path(:page => @open_bills.next_page), :class => 'load-more-bills btn btn-default', :remote => true, :onclick => "$(this).hide(); $('#spinner').show();" if @open_bills.next_page

= render partial: "shared/bills_footer_navbar", locals: {title: "Bills"}

app/views/bills/index.js.erb
$('#open_bills').append('<%= j render "bill" %>');
$('#spinner').hide();
$('[data-toggle="popover"]').popover()

<% if @open_bills.next_page %>
  $('a.load-more-bills').show();
  $('a.load-more-bills').attr('href', '<%= bills_path page: @open_bills.next_page %>');
<% else %>
  $(window).off('scroll');
  $('a.load-more-bills').remove();
<% end %>