config/routes.rb
Rails.application.routes.draw do
  
  resources :bill_payments do
    member do
      get :send_to_leads_online
    end
  end
  
  resources :bills do
    collection do
      get :line_item_fields
    end
    member do
      post :update_qb
      get :send_to_leads_online
      get :send_to_bwi
    end
  end
  
  resources :items do
    member do
      get :update_qb
    end
    collection do
      get :items_by_category
    end
  end
  
  resources :purchase_orders do
    collection do
      get :line_item_fields
    end
    member do
      post :update_qb
      get :download
      get :send_to_leads_online
    end
  end
  
  resources :purchases
  
  resources :quickbooks do
    collection do
      get :authenticate
      get :oauth_callback
    end
  end
  
  resources :vendors do
    member do
      post :update_qb
    end
  end
  
  resources :lookup_defs
  
  resources :user_settings do
    collection do
      post :set_user_location
    end
  end
  
  resources :tud_devices do
    collection do
      get :drivers_license_scan
      get :scale_read
      get :show_scanned_jpeg_image
    end
  end
  
  resources :devices do
    member do
      get :drivers_license_scan
      get :scale_read
      get :scale_camera_trigger
      get :show_scanned_jpeg_image
      get :drivers_license_camera_trigger
      get :get_signature
      get :call_printer_for_purchase_order_pdf
      get :finger_print_trigger
      get :scanner_trigger
    end
    collection do
      get :customer_camera_trigger
      get :customer_scanner_trigger
      get :customer_scale_camera_trigger
      get :customer_camera_trigger_from_ticket
      get :drivers_license_camera_trigger_from_ticket
    end
  end
  
  
  resources :jpegger_contracts
  
  require 'sidekiq/web'
  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    username == ENV["SIDEKIQ_USERNAME"] && password == ENV["SIDEKIQ_PASSWORD"]
  end if Rails.env.production?
  mount Sidekiq::Web => '/sidekiq'
  
  resources :image_files
  
  resources :shipment_files
  
  resources :cust_pic_files

  
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  
  resources :images do
    member do
      get 'show_jpeg_image'
      get 'show_preview_image'
      get 'send_pdf_data'
    end
    collection do
      get 'advanced_search'
    end
  end
  
  resources :shipments do
    member do
      get 'show_jpeg_image'
      get 'show_preview_image'
    end
  end
  
  resources :cust_pics do
    member do
      get 'show_jpeg_image'
      get 'show_preview_image'
      get 'send_pdf_data'
    end
  end
  
  resources :companies

  root 'welcome#index'
  
  get 'welcome/privacy' => 'welcome#privacy'
  get 'welcome/tos' => 'welcome#tos'
  get 'welcome/about' => 'welcome#about'
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  

end

app/models/company.rb
class Company < ActiveRecord::Base
  
  establish_connection :tud_config
  
  self.primary_key = 'CompanyID'
  self.table_name = 'Company'
  
  mount_uploader :logo_url, LogoUploader
  
  has_many :users
  has_many :workstations
  has_many :devices
  has_one :qbo_access_credential
#  has_one :jpegger_contract, foreign_key: "contract_id"
  
  #############################
  #     Instance Methods      #
  ############################
  
  def users
    User.where(location: self.CompanyID)
  end
  
  def workstations
    Workstation.where("CompanyID" => self.CompanyID)
  end
  
  def devices
    Device.where("CompanyID" => self.CompanyID)
  end
  
  def scale_devices
    Device.where(CompanyID: self.CompanyID, DeviceType: 21)
  end
  
  def device_groups
    DeviceGroup.where("CompanyID" => self.CompanyID)
  end
  
  def jpegger_contract
    JpeggerContract.where(contract_id: self.CompanyID).last
  end
  
  def leads_online_config_settings_present?
    if leads_online_store_id.blank? or leads_online_ftp_username.blank? or leads_online_ftp_password.blank?
      return false
    else
      return true
    end
  end
  
  def bwi_config_settings_present?
    if bwi_company_id.blank? or bwi_company_name.blank? or bwi_username.blank? or bwi_password.blank? or bwi_upload_url.blank?
      return false
    else
      return true
    end
  end
  
  #############################
  #     Class Methods      #
  #############################
  
  
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_company, only: [:show, :edit, :update, :destroy]
  before_action :set_oauth_client
  before_action :set_department_service, only: [:show]
  
  load_and_authorize_resource

  # GET /companies
  # GET /companies.json
  def index
#    @companies = Company.all
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
    @departments = @department_service.query(nil, :per_page => 1000)
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    respond_to do |format|
      format.html { 
        @company = Company.new(company_params)
        if @company.save
          redirect_to :back, notice: 'Company file was successfully created.' 
        else
          render :new
        end
        }
      format.json { 
        @company = Company.new(company_params)
        if @company.save
          render :show, status: :created, location: @company 
        else
          render json: @company.errors, status: :unprocessable_entity
        end
        }
      format.js {
#        @company = Company.create(user_id: 1, customer_number: "77", location: "404168351", event_code: "Photo ID", remote_file_url: "http://qb.scrapyarddog.com/tud_devices/show_scanned_jpeg_image")
        @company = Company.create(company_params)
      }
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company file was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Company file was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end
    
    def set_oauth_client
      @oauth_client = OAuth::AccessToken.new($qb_oauth_consumer, current_user.qbo_access_credential.access_token, current_user.qbo_access_credential.access_secret)
    end
    
    def set_department_service
      @department_service = Quickbooks::Service::Department.new
      @department_service.access_token = @oauth_client
      @department_service.company_id = current_company_id
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      # order matters here in that to have access to model attributes in uploader methods, they need to show up before the file param in this permitted_params list 
      params.require(:company).permit(:custom_field_1, :custom_field_1_value, :custom_field_2, :custom_field_2_value, :logo_url, 
        :leads_online_store_id, :leads_online_ftp_username, :leads_online_ftp_password, 
        :bwi_company_id, :bwi_company_name, :bwi_username, :bwi_password, :bwi_upload_url, :remove_logo_url)
    end
end

app/views/companies/_form.html.haml
= form_for @company do |f|
  - @company.errors.each do |attr, msg|
    .alert.alert-danger
      <button type="button" class="close" data-dismiss="alert">×</button>
      = "#{attr} #{msg}" if @company.errors[attr].first == msg
  .panel.panel-default
    #headingTop.panel-heading{:role => "tab"}
      %h4.panel-title
        Company Info
    .panel-body
      .row.form-group
        %div{:class => "col-sm-6"}
          = f.label "CompanyName", "Company Name", :class => "control-label"
          = f.text_field "CompanyName", :placeholder => "Company Name", class: "form-control input-lg", readonly: true
        %div{:class => "col-sm-6"}
          = f.label "CompanyId", "Company ID", :class => "control-label"
          = f.text_field "CompanyID", :placeholder => "Company ID", class: "form-control input-lg", readonly: true
      .row.form-group
        %div{:class => "col-sm-6"}
          = f.label :custom_field_1, "Custom Field 1", :class => "control-label"
          = f.text_field :custom_field_1, :placeholder => "Custom Field 1", class: "form-control input-lg"
        %div{:class => "col-sm-6"}
          = f.label :custom_field_1_value, "Custom Field 1 Value", :class => "control-label"
          = f.text_field :custom_field_1_value, :placeholder => "Custom Field 1 Value", class: "form-control input-lg"
      .row.form-group
        %div{:class => "col-sm-6"}
          = f.label :custom_field_2, "Custom Field 2", :class => "control-label"
          = f.text_field :custom_field_2, :placeholder => "Custom Field 2", class: "form-control input-lg"
        %div{:class => "col-sm-6"}
          = f.label :custom_field_2_value, "Custom Field 2 Value", :class => "control-label"
          = f.text_field :custom_field_2_value, :placeholder => "Custom Field 2 Value", class: "form-control input-lg"
      .row.form-group
        %div{:class => "col-sm-6"}
          = f.label :logo_url, "Logo", :class => "control-label"
          =# f.text_field :logo_url, :placeholder => "Logo URL", class: "form-control input-lg"
          = f.file_field :logo_url
          - unless @company.logo_url.url.blank?
            = image_tag(@company.logo_url.url, class: 'img-responsive', size: '50x50')
          = f.check_box :remove_logo_url
          Remove Logo
  #accordion.panel-group{"aria-multiselectable" => "true", :role => "tablist"}
    .panel.panel-default
      #headingOne.panel-heading{:role => "tab"}
        %h4.panel-title
          %a{"aria-controls" => "collapseOne", "aria-expanded" => "false", "data-parent" => "#accordion", "data-toggle" => "collapse", :href => "#collapseOne", :role => "button"}
            Leads Online Info
      #collapseOne.panel-collapse.collapse{"aria-labelledby" => "headingOne", :role => "tabpanel"}
        .panel-body
          .row.form-group
            %div{:class => "col-sm-6"}
              = f.label :leads_online_store_id, "Leads Online Store ID", :class => "control-label"
              = f.text_field :leads_online_store_id, :placeholder => "Leads Online Store ID", class: "form-control input-lg"
          .row.form-group
            %div{:class => "col-sm-6"}
              = f.label :leads_online_store_id, "Leads Online FTP Username", :class => "control-label"
              = f.text_field :leads_online_ftp_username, :placeholder => "Leads Online FTP Username", class: "form-control input-lg"
            %div{:class => "col-sm-6"}
              = f.label :leads_online_store_id, "Leads Online FTP Password", :class => "control-label"
              = f.text_field :leads_online_ftp_password, :placeholder => "Leads Online FTP Password", class: "form-control input-lg"
    .panel.panel-default
      #headingTwo.panel-heading{:role => "tab"}
        %h4.panel-title
          %a.collapsed{"aria-controls" => "collapseTwo", "aria-expanded" => "false", "data-parent" => "#accordion", "data-toggle" => "collapse", :href => "#collapseTwo", :role => "button"}
            BWI Info
      #collapseTwo.panel-collapse.collapse{"aria-labelledby" => "headingTwo", :role => "tabpanel"}
        .panel-body
          .row.form-group
            %div{:class => "col-sm-6"}
              = f.label :bwi_company_id, "BWI Company ID", :class => "control-label"
              = f.text_field :bwi_company_id, :placeholder => "BWI Company ID", class: "form-control input-lg"
            %div{:class => "col-sm-6"}
              = f.label :bwi_company_name, "BWI Company Name", :class => "control-label"
              = f.text_field :bwi_company_name, :placeholder => "BWI Company Name", class: "form-control input-lg"
          .row.form-group
            %div{:class => "col-sm-6"}
              = f.label :bwi_username, "BWI Username", :class => "control-label"
              = f.text_field :bwi_username, :placeholder => "BWI Username", class: "form-control input-lg"
            %div{:class => "col-sm-6"}
              = f.label :bwi_password, "BWI Password", :class => "control-label"
              = f.text_field :bwi_password, :placeholder => "BWI Password", class: "form-control input-lg"
          .row.form-group
            %div{:class => "col-sm-6"}
              = f.label :bwi_upload_url, "BWI Upload URL", :class => "control-label"
              = f.text_field :bwi_upload_url, :placeholder => "BWI Upload URL", class: "form-control input-lg"
  .row.form-group
    %div{:class => "col-sm-6"}
      = button_tag(:type => 'submit', :class => 'btn btn-primary btn-lg btn-block', data: {disable_with: "<i class='fa fa-spinner fa-spin'></i> Save"}) do
        Save

app/views/companies/edit.html.haml
= render partial: "shared/navbars/new_and_edit_company_navbar", locals: {title: truncate(@company.CompanyName, length: 12)}
- @title="#{@company.CompanyName}"

.container
  = render 'form'

app/views/companies/new.html.haml
= render partial: "shared/navbars/new_and_edit_contract_navbar", locals: {title: "Contract"}

- @title="New Contract"
.container
  = render 'form'

app/views/companies/show.html.haml
= render partial: "shared/navbars/show_company_navbar", locals: {title: @company.CompanyName}
- @title="#{@company.CompanyName}" 

.container

  %div.row
    .col-xs-12.col-sm-6.col-md-offset-3
      .panel.panel-default
        .panel-heading
          %h4.panel-title
            Company Info 
            .pull-right
              = link_to 'Edit', edit_company_path(@company)
        %ul.list-group
          %li.list-group-item
            = "Company ID:"
            .pull-right
              = "#{@company.CompanyID}" 
        %ul.list-group
          %li.list-group-item
            = "Custom Field 1:"
            .pull-right
              = "#{@company.custom_field_1}"
          %li.list-group-item
            = "Custom Field 1 Value:"
            .pull-right
              = "#{@company.custom_field_1_value}"
        %ul.list-group
          %li.list-group-item
            = "Custom Field 2:"
            .pull-right
              = "#{@company.custom_field_2}"
          %li.list-group-item
            = "Custom Field 2 Value:"
            .pull-right
              = "#{@company.custom_field_2_value}"
        %ul.list-group
          %li.list-group-item
            = "Logo:"
            - if @company.logo_url.url.blank?
              .pull-right
                None
            -#
              .pull-right
                = "#{@company.logo_url}"
          - unless @company.logo_url.url.blank?
            %li.list-group-item
              = image_tag(@company.logo_url.url, class: 'img-responsive', size: '50x50')
  %div.row
    .col-xs-12.col-sm-6.col-md-offset-3
      .panel.panel-default
        .panel-heading
          %h4.panel-title
            Quickbooks Locations 
        - unless @departments.count < 1
          - @departments.each do |department|
            %ul.list-group
              %li.list-group-item
                = department.name
        - else
          %ul.list-group
            %li.list-group-item
              No locations
      .panel.panel-default
        .panel-heading
          %h4.panel-title 
            Leads Online Info 
            .pull-right
              = link_to 'Edit', edit_company_path(@company)
        %ul.list-group
          %li.list-group-item
            = "Leads Online Store ID:"
            .pull-right
              = "#{@company.leads_online_store_id}"
          %li.list-group-item
            = "Leads Online FTP Username:"
            .pull-right
              = "#{@company.leads_online_ftp_username}"
          %li.list-group-item
            = "Leads Online FTP Password:"
            .pull-right
              = "#{@company.leads_online_ftp_password}"
      .panel.panel-default
        .panel-heading
          %h4.panel-title 
            BWI Info 
            .pull-right
              = link_to 'Edit', edit_company_path(@company)
        %ul.list-group
          %li.list-group-item
            = "BWI Company ID:"
            .pull-right
              = "#{@company.bwi_company_id}"
          %li.list-group-item
            = "BWI Company Name:"
            .pull-right
              = "#{@company.bwi_company_name}"
          %li.list-group-item
            = "BWI Username:"
            .pull-right
              = "#{@company.bwi_username}"
          %li.list-group-item
            = "BWI Password:"
            .pull-right
              = "#{@company.bwi_password}"
          %li.list-group-item
            = "BWI Upload URL:"
            .pull-right
              = "#{@company.bwi_upload_url}"
        
      
      - unless @company.jpegger_contract.blank?
        .panel.panel-default
          .panel-heading
            %h4.panel-title
              Contract
              .pull-right= link_to 'Edit', edit_jpegger_contract_path(@company.jpegger_contract)
          %ul.list-group
            %li.list-group-item
              = @company.jpegger_contract.contract_name
            %li.list-group-item= @company.jpegger_contract.verbiage.html_safe
            -#
              %li.list-group-item= link_to "Edit", edit_contract_path(current_user.default_contract.id), id: 'edit_contract_button', class: 'btn btn-primary btn-lg btn-block', data: {disable_with: "<i class='fa fa-spinner fa-spin fa-lg'></i> Edit"}
      - else
        %p.lead= link_to "New Contract", new_jpegger_contract_path

= render partial: "shared/company_footer_navbar", locals: {title: "Company"}