config/routes.rb
Rails.application.routes.draw do
  
  resources :bill_payments do
    member do
      get :send_to_leads_online
    end
  end
  
  resources :bills do
    collection do
      get :line_item_fields
    end
    member do
      post :update_qb
      get :send_to_leads_online
      get :send_to_bwi
    end
  end
  
  resources :items do
    member do
      get :update_qb
    end
    collection do
      get :items_by_category
    end
  end
  
  resources :purchase_orders do
    collection do
      get :line_item_fields
    end
    member do
      post :update_qb
      get :download
      get :send_to_leads_online
    end
  end
  
  resources :purchases
  
  resources :quickbooks do
    collection do
      get :authenticate
      get :oauth_callback
    end
  end
  
  resources :vendors do
    member do
      post :update_qb
    end
  end
  
  resources :lookup_defs
  
  resources :user_settings do
    collection do
      post :set_user_location
    end
  end
  
  resources :tud_devices do
    collection do
      get :drivers_license_scan
      get :scale_read
      get :show_scanned_jpeg_image
    end
  end
  
  resources :devices do
    member do
      get :drivers_license_scan
      get :scale_read
      get :scale_camera_trigger
      get :show_scanned_jpeg_image
      get :drivers_license_camera_trigger
      get :get_signature
      get :call_printer_for_purchase_order_pdf
      get :finger_print_trigger
      get :scanner_trigger
    end
    collection do
      get :customer_camera_trigger
      get :customer_scanner_trigger
      get :customer_scale_camera_trigger
      get :customer_camera_trigger_from_ticket
      get :drivers_license_camera_trigger_from_ticket
    end
  end
  
  
  resources :jpegger_contracts
  
  require 'sidekiq/web'
  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    username == ENV["SIDEKIQ_USERNAME"] && password == ENV["SIDEKIQ_PASSWORD"]
  end if Rails.env.production?
  mount Sidekiq::Web => '/sidekiq'
  
  resources :image_files
  
  resources :shipment_files
  
  resources :cust_pic_files

  
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  
  resources :images do
    member do
      get 'show_jpeg_image'
      get 'show_preview_image'
      get 'send_pdf_data'
    end
    collection do
      get 'advanced_search'
    end
  end
  
  resources :shipments do
    member do
      get 'show_jpeg_image'
      get 'show_preview_image'
    end
  end
  
  resources :cust_pics do
    member do
      get 'show_jpeg_image'
      get 'show_preview_image'
      get 'send_pdf_data'
    end
  end
  
  resources :companies

  root 'welcome#index'
  
  get 'welcome/privacy' => 'welcome#privacy'
  get 'welcome/tos' => 'welcome#tos'
  get 'welcome/about' => 'welcome#about'
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  

end

app/models/shipment_file.rb
class ShipmentFile < ActiveRecord::Base
  
  mount_uploader :file, ImageFileUploader
  
  belongs_to :user
  belongs_to :shipment
  belongs_to :blob
  
  after_commit :sidekiq_blob_and_shipment_creation, :on => :create # To circumvent "Can't find ModelName with ID=12345" Sidekiq error, use after_commit
  
  validates :ticket_number, presence: true
#  validates :event_code, presence: true
  
  attr_accessor :process # Virtual attribute to determine if ready to process versions
  
  
  #############################
  #     Instance Methods      #
  ############################
  
  def default_name
    self.name ||= File.basename(file_url, '.*').titleize
  end
  
  def sidekiq_blob_and_shipment_creation
    ShipmentBlobWorker.perform_async(self.id) # Create the shipment record and the blob in the background
  end
  
  #############################
  #     Class Methods         #
  #############################
  
  def self.delete_files
    require 'pathname'
    require 'fileutils'
    
    ShipmentFile.where('created_at < ? and created_at > ?', 7.days.ago, 14.days.ago).each do |shipment_file|
      if shipment_file.file.file and shipment_file.file.file.exists?
        pn = Pathname.new(shipment_file.file_url) # Get the path to the file
        shipment_file.remove_file! # Remove the file and its versions
        FileUtils.remove_dir "#{Rails.root}/public#{pn.dirname}" # Remove the now empty directory
      end
    end
  end
  
end

app/controllers/shipment_files_controller.rb
class ShipmentFilesController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_shipment_file, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource

  # GET /shipment_files
  # GET /shipment_files.json
  def index
#    @shipment_files = ShipmentFile.all
    @shipment_files = current_user.shipment_files
  end

  # GET /shipment_files/1
  # GET /shipment_files/1.json
  def show
    @ticket_number = @shipment_file.ticket_number
  end

  # GET /shipment_files/new
  def new
    @shipment_file = ShipmentFile.new
  end

  # GET /shipment_files/1/edit
  def edit
  end

  # POST /shipment_files
  # POST /shipment_files.json
  def create
    @shipment_file = ShipmentFile.new(shipment_file_params)

    respond_to do |format|
      if @shipment_file.save
#        format.html { redirect_to shipments_path, notice: 'Shipment file was successfully created.' }
#        format.html { redirect_to @shipment_file, notice: 'Shipment file was successfully created.' }
        format.html { redirect_to :back, notice: 'Shipment file was successfully created.' }
        format.json { render :show, status: :created, location: @shipment_file }
      else
        format.html { render :new }
        format.json { render json: @shipment_file.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shipment_files/1
  # PATCH/PUT /shipment_files/1.json
  def update
    respond_to do |format|
      if @shipment_file.update(shipment_file_params)
        format.html { redirect_to @shipment_file, notice: 'Shipment file was successfully updated.' }
        format.json { render :show, status: :ok, location: @shipment_file }
      else
        format.html { render :edit }
        format.json { render json: @shipment_file.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shipment_files/1
  # DELETE /shipment_files/1.json
  def destroy
    @shipment_file.destroy
    respond_to do |format|
      format.html { redirect_to shipment_files_url, notice: 'Shipment file was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shipment_file
      @shipment_file = ShipmentFile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shipment_file_params
      # order matters here in that to have access to model attributes in uploader methods, they need to show up before the file param in this permitted_params list 
      params.require(:shipment_file).permit(:ticket_number, :name, :file, :user_id, :customer_number, :branch_code, :location, :event_code, :shipment_id, :container_number, :booking_number, :contract_number, :hidden, :blob_id)
    end
end

app/views/shipment_files/_form.html.haml
= form_for @image_file do |f|
  - if @image_file.errors.any?
    #error_explanation
      %h2= "#{pluralize(@image_file.errors.count, "error")} prohibited this image_file from being saved:"
      %ul
        - @image_file.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :file
    = f.text_field :file
  .field
    = f.label :user_id
    = f.number_field :user_id
  .field
    = f.label :ticket_number
    = f.text_field :ticket_number
  .field
    = f.label :customer_number
    = f.text_field :customer_number
  .field
    = f.label :branch_code
    = f.text_field :branch_code
  .field
    = f.label :location
    = f.text_field :location
  .field
    = f.label :event_code
    = f.text_field :event_code
  .field
    = f.label :image_id
    = f.number_field :image_id
  .field
    = f.label :container_number
    = f.text_field :container_number
  .field
    = f.label :booking_number
    = f.text_field :booking_number
  .field
    = f.label :contract_number
    = f.text_field :contract_number
  .field
    = f.label :hidden
    = f.check_box :hidden
  .field
    = f.label :blob_id
    = f.number_field :blob_id
  .actions
    = f.submit 'Save'

app/views/shipment_files/_upload_modal.html.haml
%div{:id => "upload_form", :class => "modal fade", :tabindex => "-1", :style => "display:none;"}
  = form_for ShipmentFile.new do |f|
    .modal-dialog.modal-sm
      .modal-content
        -#
          .modal-header
            = link_to "×", '#', :class => "close", "data-dismiss" => "modal"
            %strong New Picture
        .modal-body
          = f.hidden_field :user_id, value: current_user.id
          .form-group
            = f.label "Ticket Number*", :class => 'control-label'
            -#
              .input-group
            = f.text_field :ticket_number, :placeholder => "Ticket Number", value: @ticket_number, class: "form-control input-lg", autofocus: true, required: true
            -#
              %span.input-group-addon 
                %a{href: '#', onclick: "$('#shipment_file_ticket_number').val('');"}
                  %i.fa.fa-remove.fa-lg
          .form-group{:id => "event_code"}
            = f.label "Event Code*", :class => 'control-label'
            =# f.select :event_code, options_for_select(Shipment.event_codes.map(&:event_code)), {prompt: "Select event code"}, {:class => "form-control input-lg", required: true}
            =# f.text_field :event_code, :placeholder => "Event Code", class: "form-control typeahead input-lg", data: { events: "#{Shipment.event_codes.map(&:event_code)}"}, required: true
            =# f.text_field :event_code, :placeholder => "Event Code", class: "form-control typeahead input-lg", data: { events: "#{LookupDef.shipment_event_codes.map(&:LookupDisplay)}"}, required: true
            =# f.select :event_code, options_for_select(Shipment.event_codes.map(&:event_code)), {prompt: "Select event code"}, {:class => "form-control input-lg", required: true}
            = f.select :event_code, options_for_select(LookupDef.shipment_event_codes.map(&:LookupValue)), {prompt: "Select event code"}, {:class => "form-control input-lg", required: true}
          .form-group
            = f.label "File*", :class => 'control-label'
            = f.file_field :file, title: "<i class='fa fa-photo'/> Choose image".html_safe, class: 'btn btn-warning', required: true
        .modal-footer
          %button.btn.btn-default.btn-lg{"data-dismiss" => "modal", :type => "button"} x
          = button_tag(:type => 'submit', :class => 'btn btn-primary btn-lg', id: "new_shipment_file_submit") do
            Upload
            %i.fa.fa-arrow-up

:javascript
  //$('input[type=file]').bootstrapFileInput();

  //Required attribute fallback
  function attributeSupported(attribute) {
    return (attribute in document.createElement("input"));
  }
  function isSafariOnly() {
    return navigator.userAgent.indexOf('Safari') != -1 && navigator.userAgent.indexOf('Chrome') == -1;
  }
  $(function () {
    $('#new_shipment_file').submit(function () {
      if (!attributeSupported("required") || isSafariOnly()) {
        $("#new_shipment_file [required]").each(function (index) {
          if (!$(this).val()) {
            alert("Please Fill In All Required Fields.");
            return false;
          }
        });
      }
      return true;
    });
  });

  // Don't allow for form submit until form fields completed
  //$("#new_shipment_file_submit").attr("disabled", "disabled");
  $("#new_shipment_file_submit").hide();

  // Make check if ticket number changes
  $("#shipment_file_ticket_number").on("change", function() {
    if($("#shipment_file_ticket_number").val() && $("#shipment_file_file").val() && $("#shipment_file_event_code").val()) {
      //$("#new_shipment_file_submit").removeAttr("disabled");
      $("#new_shipment_file_submit").show();
    }
    else {
      //$("#new_shipment_file_submit").attr("disabled", "disabled");
      $("#new_shipment_file_submit").hide();
    }
  });

  // Make check if file changes
  $("#shipment_file_file").on("change", function() {
    if($("#shipment_file_ticket_number").val() && $("#shipment_file_file").val() && $("#shipment_file_event_code").val()) {
      //$("#new_shipment_file_submit").removeAttr("disabled");
      $("#new_shipment_file_submit").show();
    }
    else {
      //$("#new_shipment_file_submit").attr("disabled", "disabled");
      $("#new_shipment_file_submit").hide();
    }
  });

  // Make check if event code changes
  $("#shipment_file_event_code").on("change", function() {
    if($("#shipment_file_ticket_number").val() && $("#shipment_file_file").val() && $("#shipment_file_event_code").val()) {
      //$("#new_shipment_file_submit").removeAttr("disabled");
      $("#new_shipment_file_submit").show();
    }
    else {
      //$("#new_shipment_file_submit").attr("disabled", "disabled");
      $("#new_shipment_file_submit").hide();
    }
  });

app/views/shipment_files/edit.html.haml
%h1 Editing image_file

= render 'form'

= link_to 'Show', @image_file
\|
= link_to 'Back', image_files_path

app/views/shipment_files/index.html.haml
%h1 Listing image_files

%table
  %thead
    %tr
      %th Name
      %th File
      %th User
      %th Ticket number
      %th Customer number
      %th Branch code
      %th Location
      %th Event code
      %th Image
      %th Container number
      %th Booking number
      %th Contract number
      %th Hidden
      %th Blob
      %th
      %th
      %th

  %tbody
    - @image_files.each do |image_file|
      %tr
        %td= image_file.name
        %td= image_file.file
        %td= image_file.user_id
        %td= image_file.ticket_number
        %td= image_file.customer_number
        %td= image_file.branch_code
        %td= image_file.location
        %td= image_file.event_code
        %td= image_file.image_id
        %td= image_file.container_number
        %td= image_file.booking_number
        %td= image_file.contract_number
        %td= image_file.hidden
        %td= image_file.blob_id
        %td= link_to 'Show', image_file
        %td= link_to 'Edit', edit_image_file_path(image_file)
        %td= link_to 'Destroy', image_file, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Image file', new_image_file_path

app/views/shipment_files/new.html.haml
%h1 New image_file

= render 'form'

= link_to 'Back', image_files_path

app/views/shipment_files/show.html.haml
= render partial: "shared/search_navbar", locals: {title: "#{@shipment_file.ticket_number}"}
.container
  %div.row
    .col-xs-12.col-sm-6.col-md-offset-3
      = link_to image_tag(@shipment_file.file_url, alt: @shipment_file.id, class: 'img-responsive'), "#shipment_popup", "data-toggle" => "modal", :alt => "Image", :class => 'thumbnail'
  %div{:id => "shipment_popup", :class => "modal fade", :tabindex => "-1", :style => "display:none;"}
    .modal-dialog.modal-lg
      .modal-content
        .modal-body
          = image_tag(@shipment_file.file_url, alt: @shipment_file.id, class: 'img-responsive')
  %div.row
    .col-xs-12.col-sm-6.col-md-offset-3
      %div.panel.panel-primary
        %div.list_group
          - unless @shipment_file.event_code.blank?
            %div.list-group-item
              %strong= "Event:"
              .pull-right
                = "#{@shipment_file.event_code}"
          %div.list-group-item
            %strong= "Date/Time:"
            .pull-right
              = "#{@shipment_file.created_at.strftime("%-m/%-d/%y %l:%M %p")}"

= render partial: "shared/footer_navbar", locals: {title: "Shipments"}


-#
  %p#notice= notice

  %p
    %b Ticket number:
    = @shipment_file.ticket_number
  %p
    %b File:
    = image_tag(@shipment_file.file)

  -#
    %p
      %b User:
      = @shipment_file.user_id
    %p
      %b Name:
      = @shipment_file.name
    %p
      %b Customer number:
      = @shipment_file.customer_number
    %p
      %b Branch code:
      = @shipment_file.branch_code
    %p
      %b Location:
      = @shipment_file.location
    %p
      %b Event code:
      = @shipment_file.event_code
    %p
      %b Image:
      = @shipment_file.shipment_id
    %p
      %b Container number:
      = @shipment_file.container_number
    %p
      %b Booking number:
      = @shipment_file.booking_number
    %p
      %b Contract number:
      = @shipment_file.contract_number
    %p
      %b Hidden:
      = @shipment_file.hidden
    %p
      %b Blob:
      = @shipment_file.blob_id

    = link_to 'Edit', edit_shipment_file_path(@shipment_file)
    \|
    = link_to 'Back', shipment_files_path